function [PawLick2p]= GetDLC_2p (filename)
%IMPORTFILE Import data from a text file
%  VID20220302T110853DLCMOBNET1002PPAWLICKTRACKINGMAR8SHUFFLE15000 =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  VID20220302T110853DLCMOBNET1002PPAWLICKTRACKINGMAR8SHUFFLE15000 =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Vid20220302T110853DLCmobnet1002PPawLickTrackingMar8shuffle15000 = importfile("Z:\homes\kleej02\Data\JK38\2Photon\SoundExperiment\JK38_SoundExpLong_1.5Zoom_PostGoNoGo_OnlyTones_TSeries-03022022-1101-156\JK38_SoundExperimentLongPost_2022-03-02T11-08-52\Vid2022-03-02T11_08_53DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_50000.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Mar-2022 20:38:51

%% Input handling


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify column names and types
opts.VariableNames = ["scorer", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_50000", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_1", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_2", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_3", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_4", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_5", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_6", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_7", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_8", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_9", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_10", "DLC_mobnet_100_2P_PawLickTrackingMar8shuffle1_11"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PawLick2p= table2array(readtable(filename, opts));

end