function [FPaw_Lick_DLC] = Get_DLC(filename, dataLines)
%IMPORTFILE Import data from a text file
%  JK27PREBV20210913T153216DLCMOBNET100PAWLICKTRACKINGSEP25SHUFFLE =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  JK27PREBV20210913T153216DLCMOBNET100PAWLICKTRACKINGSEP25SHUFFLE =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  JK27preBV20210913T153216DLCmobnet100PawLicktrackingSep25shuffle = importfile("/Users/Jan/Desktop/GoTone_2021-09-13T15-32-16/JK27_pre_BV2021-09-13T15_32_16DLC_mobnet_100_PawLicktrackingSep25shuffle1_30000.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Sep-2021 20:48:12

%% Input handling


    dataLines = [4, Inf];


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["scorer", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_30000", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_1", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_2", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_3", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_4", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_5", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_6", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_7", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_8", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_9", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_10", "DLC_mobnet_100_PawLicktrackingSep25shuffle1_11"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data

FPaw_Lick_DLC= readtable(filename, opts);

end