function TextFile = Get_TextFile(filename)
%IMPORTFILE Import data from a text file
%  QUARTERATT70DB1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  QUARTERATT70DB1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  quarterATT70dB1 = importfile("Z:\homes\kleej02\Data\JK69\2Photon\SoundExperiment\JK69_SoundsExpLong_TD_TSeries-04192022-1452-187\JK69_LongSound_TD_2022-04-19T15-47-25\quarter_ATT_70dB_1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Apr-2022 09:16:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
TextFile = table2array(readtable(filename, opts));

end