function Optopara = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OPTOPARA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  OPTOPARA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Optopara = importfile("/Volumes/sippylab/homes/kleej02/Data/JK20/Pretraining_2021-08-27T10-19-00/JK20_OPTOpara2021-08-27T10_19_00.csv", [1, 1]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Aug-2021 16:37:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["StimDuration", "StimFreq", "StimDutyCycle", "Power_PatchTip"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["StimDuration", "StimFreq", "StimDutyCycle", "Power_PatchTip"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["StimDuration", "StimFreq", "StimDutyCycle", "Power_PatchTip"], "ThousandsSeparator", ",");

% Import the data
Optopara = readtable(filename, opts);

end