function GoToneStateTransitions = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GOTONESTATETRANSITIONS = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  GOTONESTATETRANSITIONS = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  GoToneStateTransitions = importfile("/Users/janklee/Desktop/GoTone_11Khz_ResponseTones_2023-06-26T20-11-13/GoTone_StateTransitions.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jun-2023 21:05:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
%opts.VariableNames = ["Trial", "Id", "ElapsedTime", "TimeOfDay"];
%opts.VariableTypes = ["double", "categorical", "double", "double"];

% Specify column names and types
opts.VariableNames = ["TimeOfDay", "Trial", "Id", "ElapsedTime"];
opts.SelectedVariableNames = ["TimeOfDay", "Trial", "Id", "ElapsedTime"];
opts.VariableTypes = ["double", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Id", "EmptyFieldRule", "auto");

% Import the data
GoToneStateTransitions = readtable(filename, opts);

end