function VideoTimestamps = Get_VideoTimestamps(filename)
%IMPORTFILE Import data from a text file
%  VIDEOTIMESTAMPS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  VIDEOTIMESTAMPS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  VideoTimestamps = importfile("/Volumes/sippylab/homes/kleej02/Data/JK69/2Photon/SoundExperiment/JK69_SoundExpLong_TSeries-05122022-1649-213/JK69_SoundExpLong_2022-05-12T17-02-43/VideoTimestamps.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-May-2022 19:06:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Set all variable names and types
opts.VariableNames = strcat("Var", string(1:17));
opts.VariableTypes = {'double', 'double', 'double', 'char', 'char', 'double', 'double', 'double', 'double','double', 'double', 'double', 'double','double', 'double', 'char', 'double'};

% Select only the 17th column
opts.SelectedVariableNames = "Var17";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
VideoTimestamps = table2array(readtable(filename, opts));

end