function [PhotometryFrames] = GetBonsai_PhotometryFrames(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FRAMES20230626T144653 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  FRAMES20230626T144653 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Frames20230626T144653 = importfile("/Volumes/sippylab/Data/Jan Klee/JK214/Photometry/GoNoGo_ResponseSoundsPuff/GoTone_11Khz_ResponseTones_2023-06-26T14-46-53/Frames2023-06-26T14_46_53.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jun-2023 18:06:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Item1", "Item2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PhotometryFrames = readtable(filename, opts);

end