function Photometry = GetBonsai_Photometry(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PHOTOMETRY20230726T134741 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  PHOTOMETRY20230726T134741 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Photometry20230726T134741 = importfile("Z:\homes\kleej02\Data\M1\JK247\Pretraining_2023-07-26T13-47-40\Photometry_2023-07-26T13_47_41.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jul-2023 09:24:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FrameCounter", "Timestamp", "LedState", "Stimulation", "Output0", "Output1", "Input0", "Input1", "Region0R", "Region1R", "Region2R", "Region3R", "Region4R", "Region5R", "Region6R", "Region7R", "Region8G", "Region9G", "Region10G", "Region11G", "Region12G", "Region13G", "Region14G", "Region15G"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Photometry = readtable(filename, opts);

end