function sounds = GetBonsai_Sounds(filename)
%IMPORTFILE Import data from a text file
%  SOUNDS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  SOUNDS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  sounds = importfile("Z:\homes\kleej02\Data\JK44\2Photon\SoundExperiement\JK44_Soundtes_13Zoom_300Down_TSeries-01142022-1542-064\2022-01-14T15-52-27\sounds.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jan-2022 10:58:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
sounds = table2array(readtable(filename, opts));

end