function FrameTSduringBehavior = GetBonsai_FrameTS_duringBehavior(filename)
%IMPORTFILE Import data from a text file
%  FRAMETSDURINGBEHAVIOR = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  FRAMETSDURINGBEHAVIOR = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  FrameTSduringBehavior = importfile("Z:\Data\Jan Klee\JK323\2Photon\Switching\JK323_SwitchingTest2_TSeries-07232024-1143-1693\SwitchingSync_File_2024-07-23T11-51-11\FrameTS_during_Behavior.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Jul-2024 17:56:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
FrameTSduringBehavior = table2array(readtable(filename, opts));

end